### ISSUE TITLE
Dropships history page

### ISSUE THREAD

**Issue by solevis** [solevis/pixyship#28]

**Comment by Gedili** [comment]
Related to :https://github.com/solevis/pixyship/issues/7

Store everyday sales, both from shop sale, IAP and dropship:
Table with ItemDeignId / ItemDesignName (redudant maybe, to avoid joint queries with the ItemDesigns table) / Currency (include IAP, on top of Starbux, Gas, Mineral) / Currency Price (min pack in the case of IAP bonus) / Type (Shop, Dropship, IAP) / Date

**Comment by Zukunftsmusik** [comment]
Dolores 2.0 has an export feature for the past shop/catalog sales so hit me up, when you need something.

Also @Gedili the db should store the entity id (item, room or crew) along the entity type, not just ItemDesignId. At least for shop/catalog sales and IAP promotions.

If you need help on retrieving the promotion information (IAP bonus), hit me up on Discord.

**Comment by solevis** [comment]
Done in 9db42184b5126d94ad01ff50b6c3bd2f8cffea05
