### ISSUE TITLE
Add the buyer/seller to the market sales

### ISSUE THREAD

**Issue by Gedili** [solevis/pixyship#29]
Store the buyer and seller name on the market monitor, so that the item single page can display the last sales, similarly to OrionBoard.

On that last sales table, add Currency/ Amount / Price (unitary) / ItemName / Seller / Buyer / Date
add filters to choose the currecy, filter seller/buyers, select a date range,  order by price, etc

**Comment by solevis** [comment]
I already store buyer and seller name of each sales.
