### ISSUE TITLE
Add a crafts info page

### ISSUE THREAD

**Issue by Zukunftsmusik** [solevis/pixyship#33]
Info on crafts is something that's currently missing (our outdated) in any other of the 3rd party tools.

**Comment by solevis** [comment]
What you mean by crafts? In https://github.com/solevis/pixyship/issues/18 I proposed to display craft recipe as tree, it's the same thing you propose ?

For example, item A need B + C, and B need D + E, the page will display something like:

                       
```
               A       
               |       
               |       
       B ------+----- C
       |               
       |               
 D ----+--- E
```

**Comment by Zukunftsmusik** [comment]
No I mean info on Hangar crafts like Defenders, Stingers etc. ^^

**Comment by solevis** [comment]
Ok! I better understand now 😄

**Comment by solevis** [comment]
Endpoint: `RoomService/ListCraftDesigns` and `RoomService/ListMissileDesigns`
