### ISSUE TITLE
blacklist terms in filters

### ISSUE THREAD

**Issue by Gedili** [solevis/pixyship#36]
When using a blacklist term alone in the filter field (-professor) it works fine, showing all that doesn't satisfy that criteria. However when paired with whitelist terms if fails. 

If you search:   A,B,C it'll give all the elements satisfying A or B or C
if you search:   A,B,-C, currently it'll give all the elements satisfying A or B or (not C), since (not C) usually include almost every elements, it doesn't make sense. It should be (A or B) AND (not C). Have the blacklist term only applied to the white list selection. Don't know how it's implemented, if it make it easier you could pair each positive term with the combination of negative terms, so that A,B,C,-D,-E gives (A and -D and -E) OR (B and -D and -E) OR (C and -D and -E).

This would allow searches like "Zombie,Taura,Mummy,-cat", or in the ship page "Pirate,Federation,Qtarian,-extended,-hybrid,-assault"

**Comment by solevis** [comment]
Done in v2
