### ISSUE TITLE
Display explosion radius of crafts and missiles

### ISSUE THREAD

**Issue by solevis** [solevis/pixyship#87]

**Comment by Zukunftsmusik** [comment]
The radius is being displayed as pixels in game.
Just divide the value in the API by 4 to get the pixels.
25 pixels are 1 grid btw. But the grid count depends on the width & height of the room being hit.

**Comment by solevis** [comment]
@Zukunftsmusik so the BFR with 400 in API just have a 16 pixels explosion radius? That doesn't sound like much

**Comment by solevis** [comment]
Forget it. I checked in the game and it's listed as AOE and it's the api value divided by 100.
